### PR TITLE
new files and gitignore

### PR DESCRIPTION
**Pull request by emilyb7**

### CODE REVIEW

**Comment by shiryz** [comment]
fixes #9

**Comment by des-des** [comment]
yoyo, no pr description, issue against commit etc. pls assign to me! @emilyb7 @shiryz

**Comment by shiryz** [comment]
@des-des , are you sure you want to check issues like these ones, we just set up empty files.
will assign you to every other one from on :sweat_smile:

**Comment by des-des** [comment]
Yeah, sorry to be annoying!

**Pull request merged**
